# this file contains all the precompiles generated by using precompile.jl

# these precompiles do not cause the segfault
precompile(Tuple{typeof(Base.:(!=)), UInt64, UInt64})
precompile(Tuple{typeof(Base.invokelatest), Any})
precompile(Tuple{Base.var"##s78#203", Any, Any, Any, Any, Any})
precompile(Tuple{typeof(Base.merge_types), Tuple{Vararg{Symbol}}, Type{var"#s78"} where var"#s78"<:(NamedTuple{names, T} where T<:Tuple where names), Type{var"#s77"} where var"#s77"<:(NamedTuple{names, T} where T<:Tuple where names)})
precompile(Tuple{Core.Compiler.var"#273#274", Any, Any})
precompile(Tuple{typeof(Base.uv_asynccb), Ptr{Nothing}})
precompile(Tuple{typeof(AWSCRT.__init__)})
precompile(Tuple{typeof(AWSCRT.on_connection_complete), Ptr{LibAWSCRT.aws_mqtt_client_connection}, Int32, Int32, UInt8, Ptr{Nothing}})

# including the below precompiles causes the segfault
precompile(Tuple{typeof(Foo.start)})
