name: VersionVigilante

on:
  pull_request:
    branches:
      - main
    paths-ignore:
      - ".github/**"
      - "Project.toml"
      - "README.md"
      - "dev/**"

jobs:
  VersionVigilante:
    runs-on: ubuntu-latest
    timeout-minutes: 10

    permissions:
      contents: write
      pull-requests: write
      actions: write

    steps:
      - name: Cancel Previous Runs
        uses: styfle/cancel-workflow-action@d07a454dad7609a92316b57b23c9ccfd4f59af66 # 0.13.1
        with:
          access_token: ${{ github.token }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: julia-actions/setup-julia@4c0cb0fce8556fdb04a90347310e5db8b1f98fb9 # v2.7.0
        with:
          version: 1.6
      - name: VersionVigilante.main
        id: versionvigilante_main
        run: |
          julia -e 'using Pkg; Pkg.add("VersionVigilante")'
          julia -e 'using VersionVigilante; VersionVigilante.main("https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}"; master_branch="main")'
      - name: ✅ Un-Labeller (if success)
        if: (steps.versionvigilante_main.outputs.compare_versions == 'success') && (success() || failure())
        continue-on-error: true
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.removeLabel({...context.issue, name: 'needs version bump'})
      - name: ❌ Labeller (if failure)
        if: (steps.versionvigilante_main.outputs.compare_versions == 'failure') && (success() || failure())
        continue-on-error: true
        uses: actions/github-script@ed597411d8f924073f98dfc5c65a23a2325f34cd # v8.0.0
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            github.issues.addLabels({...context.issue, labels: ['needs version bump']})
